"""A plain-language summary as a document (EF-CON-01, tranche 4.1), in French or English:
the summary a person revised, then its readability index against the target of its
level. A level without a revised summary says so; the AI's draft is never shown."""

from collections.abc import Callable
from datetime import datetime

from revue_portee.domain.lay_summary import TARGET_INDEX, LayLevel, LaySummary, meets_target
from revue_portee.domain.readability import Band
from revue_portee.i18n import translator
from revue_portee.reporting.document import Block, Document, Heading, Paragraph
from revue_portee.reporting.formats import date, fixed, integer

__all__ = ["band_labels", "build_lay_summary", "level_labels"]

type Translate = Callable[[str], str]


def level_labels(_: Translate) -> dict[LayLevel, str]:
    return {
        LayLevel.GENERAL: _("general public"),
        LayLevel.INFORMED: _("informed readers"),
        LayLevel.PROFESSIONAL: _("professionals"),
    }


def band_labels(_: Translate) -> dict[Band, str]:
    return {
        Band.VERY_EASY: _("very easy"),
        Band.EASY: _("easy"),
        Band.FAIRLY_EASY: _("fairly easy"),
        Band.STANDARD: _("standard"),
        Band.FAIRLY_DIFFICULT: _("fairly difficult"),
        Band.DIFFICULT: _("difficult"),
        Band.VERY_DIFFICULT: _("very difficult"),
    }


def build_lay_summary(
    summary: LaySummary | None,
    *,
    level: LayLevel,
    review_title: str,
    language: str,
    outdated: bool,
    tool_version: str,
    generated_at: datetime,
) -> Document:
    _ = translator(language)
    level_name = level_labels(_)[level]
    title = (summary.title if summary is not None and summary.title else
             _("{title}: plain-language summary").format(title=review_title))  # fmt: skip
    blocks: list[Block] = [
        Heading(level=1, text=title),
        Paragraph(
            text=_(
                "Plain-language summary of the scoping review « {review} », for {level}. "
                "Generated by revue-portee {version} on {date}."
            ).format(
                review=review_title, level=level_name, version=tool_version, date=date(generated_at)
            )
        ),
    ]
    if summary is None:
        blocks.append(
            Paragraph(text=_("To be written: no revised summary for this level."), placeholder=True)
        )
        return Document(title=title, language=language, generated_at=generated_at,
                        blocks=tuple(blocks))  # fmt: skip
    if outdated:
        blocks.append(
            Paragraph(
                text=_("To be reviewed: the narrative synthesis was revised since this summary."),
                placeholder=True,
            )
        )
    blocks += [Paragraph(text=p) for p in summary.paragraphs]
    found = summary.readability
    if found is not None:
        target = TARGET_INDEX[level]
        reached = _("target reached") if meets_target(level, found) else _("target not reached")
        blocks += [
            Heading(level=2, text=_("Readability")),
            Paragraph(
                text=_(
                    "Readability index ({formula}): {index} ({band}); target for {level}: "
                    "{target} or more ({reached}). Counted on {words} words, {sentences} "
                    "sentences and {syllables} syllables. The summary was revised by a "
                    "person; the index is a guide, not a guarantee of understanding."
                ).format(
                    formula=found.formula,
                    index=fixed(found.index, 1, language),
                    band=band_labels(_)[found.band],
                    level=level_name,
                    target=fixed(target, 0, language),
                    reached=reached,
                    words=integer(found.words, language),
                    sentences=integer(found.sentences, language),
                    syllables=integer(found.syllables, language),
                )
            ),
        ]
    return Document(title=title, language=language, generated_at=generated_at,
                    blocks=tuple(blocks))  # fmt: skip
