"""The narrative synthesis as a document (EF-SYN-04, tranche 3.6), in French or English.

One section per field of the grid: the sentences a person revised, each followed by the
studies it rests on; a field whose draft no person has revised says so, and the AI's
draft is never shown. The studies cited are listed at the end.
"""

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime

from revue_portee.domain.grid import GridField
from revue_portee.domain.narrative import NarrativeDraft
from revue_portee.i18n import translator
from revue_portee.reporting.document import Block, BulletList, Document, Heading, Paragraph
from revue_portee.reporting.formats import date, separator

__all__ = ["NarrativeSection", "build_narrative", "cited"]

type Translate = Callable[[str], str]


@dataclass(frozen=True, slots=True)
class NarrativeSection:
    field: GridField
    revised: NarrativeDraft | None  # the latest draft a person revised
    outdated: bool = False  # values or field changed since the revision


def cited(sentence_ids: Sequence[str], labels: Mapping[str, str], language: str) -> str:
    """« (Roy et al. 2019; Tremblay 2019) », in the order of the labels."""
    names = sorted((labels.get(i, i) for i in sentence_ids), key=str.casefold)
    return "(" + separator(language).join(names) + ")"


def _section(_: Translate, section: NarrativeSection, labels: Mapping[str, str],
             language: str) -> list[Block]:  # fmt: skip
    blocks: list[Block] = [Heading(level=2, text=f"{section.field.code} — {section.field.label}")]
    if section.revised is None:
        blocks.append(
            Paragraph(
                text=_("To be written: no revised synthesis of this field."), placeholder=True
            )
        )
        return blocks
    if section.outdated:
        blocks.append(
            Paragraph(
                text=_("To be reviewed: values or the field changed since this revision."),
                placeholder=True,
            )
        )
    blocks.append(
        Paragraph(
            text=" ".join(
                f"{s.text.strip().removesuffix('.')} {cited(s.study_ids, labels, language)}."
                for s in section.revised.sentences
            )
        )
    )
    return blocks


def build_narrative(
    sections: Sequence[NarrativeSection],
    references: Sequence[tuple[str, str, str]],  # id, label, full reference
    *,
    project_title: str,
    language: str,
    tool_version: str,
    generated_at: datetime,
) -> Document:
    _ = translator(language)
    labels = {ref_id: label for ref_id, label, _full in references}
    used = {i for s in sections if s.revised for p in s.revised.sentences for i in p.study_ids}
    title = _("{title}: narrative synthesis (draft)").format(title=project_title)
    blocks: list[Block] = [
        Heading(level=1, text=title),
        Paragraph(
            text=_(
                "Generated by revue-portee {version} on {date}. Every sentence was revised by "
                "a person and rests on the included studies cited after it."
            ).format(version=tool_version, date=date(generated_at))
        ),
    ]
    for section in sections:
        blocks += _section(_, section, labels, language)
    cited_refs = [f"{label}. {full}" for ref_id, label, full in references if ref_id in used]
    if cited_refs:
        blocks += [
            Heading(level=2, text=_("Studies cited")),
            BulletList(items=tuple(sorted(cited_refs, key=str.casefold))),
        ]
    return Document(title=title, language=language, generated_at=generated_at, blocks=tuple(blocks))
